FROM anyenv:py-3.7

ENV PYTHON_VERSION 3.7.4
RUN source ~/.bashrc && \
	anyenv install pyenv && \
	git clone https://github.com/yyuu/pyenv-virtualenv ${HOME}/.anyenv/envs/pyenv/plugins/pyenv-virtualenva && \
	source ~/.bashrc && \
	pyenv install $PYTHON_VERSION && \
        echo 'eval "$(pyenv init -)"' >> ${HOME}/.bashrc && \
        echo 'eval "$(pyenv virtualenv-init -)"' >> ${HOME}/.bashrc 


CMD /bin/bash

